// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: messaging.proto

package skyrush

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SkyRushClient is the client API for SkyRush service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkyRushClient interface {
	RoundCashout(ctx context.Context, in *RoundBet, opts ...grpc.CallOption) (*RoundCashoutResponse, error)
	PlaceRoundBet(ctx context.Context, in *RoundBet, opts ...grpc.CallOption) (*PlaceRoundBetResponse, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	CancelRoundBet(ctx context.Context, in *RoundBet, opts ...grpc.CallOption) (*CancelRoundBetResponse, error)
	GetRoundBets(ctx context.Context, in *GetRoundBetsRequest, opts ...grpc.CallOption) (*GetRoundBetsResponse, error)
	GetRoundSettings(ctx context.Context, in *GetRoundSettingsRequest, opts ...grpc.CallOption) (*RoundSettings, error)
	GetActiveBets(ctx context.Context, in *GetActiveBetsRequest, opts ...grpc.CallOption) (*GetActiveBetsResponse, error)
	GetRoundHistory(ctx context.Context, in *GetRoundHistoryRequest, opts ...grpc.CallOption) (*GetRoundHistoryResponse, error)
	UpdateRoundSettings(ctx context.Context, in *RoundSettings, opts ...grpc.CallOption) (*UpdateRoundSettingsResponse, error)
}

type skyRushClient struct {
	cc grpc.ClientConnInterface
}

func NewSkyRushClient(cc grpc.ClientConnInterface) SkyRushClient {
	return &skyRushClient{cc}
}

func (c *skyRushClient) RoundCashout(ctx context.Context, in *RoundBet, opts ...grpc.CallOption) (*RoundCashoutResponse, error) {
	out := new(RoundCashoutResponse)
	err := c.cc.Invoke(ctx, "/SkyRush/RoundCashout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyRushClient) PlaceRoundBet(ctx context.Context, in *RoundBet, opts ...grpc.CallOption) (*PlaceRoundBetResponse, error) {
	out := new(PlaceRoundBetResponse)
	err := c.cc.Invoke(ctx, "/SkyRush/PlaceRoundBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyRushClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, "/SkyRush/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyRushClient) CancelRoundBet(ctx context.Context, in *RoundBet, opts ...grpc.CallOption) (*CancelRoundBetResponse, error) {
	out := new(CancelRoundBetResponse)
	err := c.cc.Invoke(ctx, "/SkyRush/CancelRoundBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyRushClient) GetRoundBets(ctx context.Context, in *GetRoundBetsRequest, opts ...grpc.CallOption) (*GetRoundBetsResponse, error) {
	out := new(GetRoundBetsResponse)
	err := c.cc.Invoke(ctx, "/SkyRush/GetRoundBets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyRushClient) GetRoundSettings(ctx context.Context, in *GetRoundSettingsRequest, opts ...grpc.CallOption) (*RoundSettings, error) {
	out := new(RoundSettings)
	err := c.cc.Invoke(ctx, "/SkyRush/GetRoundSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyRushClient) GetActiveBets(ctx context.Context, in *GetActiveBetsRequest, opts ...grpc.CallOption) (*GetActiveBetsResponse, error) {
	out := new(GetActiveBetsResponse)
	err := c.cc.Invoke(ctx, "/SkyRush/GetActiveBets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyRushClient) GetRoundHistory(ctx context.Context, in *GetRoundHistoryRequest, opts ...grpc.CallOption) (*GetRoundHistoryResponse, error) {
	out := new(GetRoundHistoryResponse)
	err := c.cc.Invoke(ctx, "/SkyRush/GetRoundHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyRushClient) UpdateRoundSettings(ctx context.Context, in *RoundSettings, opts ...grpc.CallOption) (*UpdateRoundSettingsResponse, error) {
	out := new(UpdateRoundSettingsResponse)
	err := c.cc.Invoke(ctx, "/SkyRush/UpdateRoundSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkyRushServer is the server API for SkyRush service.
// All implementations should embed UnimplementedSkyRushServer
// for forward compatibility
type SkyRushServer interface {
	RoundCashout(context.Context, *RoundBet) (*RoundCashoutResponse, error)
	PlaceRoundBet(context.Context, *RoundBet) (*PlaceRoundBetResponse, error)
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	CancelRoundBet(context.Context, *RoundBet) (*CancelRoundBetResponse, error)
	GetRoundBets(context.Context, *GetRoundBetsRequest) (*GetRoundBetsResponse, error)
	GetRoundSettings(context.Context, *GetRoundSettingsRequest) (*RoundSettings, error)
	GetActiveBets(context.Context, *GetActiveBetsRequest) (*GetActiveBetsResponse, error)
	GetRoundHistory(context.Context, *GetRoundHistoryRequest) (*GetRoundHistoryResponse, error)
	UpdateRoundSettings(context.Context, *RoundSettings) (*UpdateRoundSettingsResponse, error)
}

// UnimplementedSkyRushServer should be embedded to have forward compatible implementations.
type UnimplementedSkyRushServer struct {
}

func (UnimplementedSkyRushServer) RoundCashout(context.Context, *RoundBet) (*RoundCashoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoundCashout not implemented")
}
func (UnimplementedSkyRushServer) PlaceRoundBet(context.Context, *RoundBet) (*PlaceRoundBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceRoundBet not implemented")
}
func (UnimplementedSkyRushServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSkyRushServer) CancelRoundBet(context.Context, *RoundBet) (*CancelRoundBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRoundBet not implemented")
}
func (UnimplementedSkyRushServer) GetRoundBets(context.Context, *GetRoundBetsRequest) (*GetRoundBetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoundBets not implemented")
}
func (UnimplementedSkyRushServer) GetRoundSettings(context.Context, *GetRoundSettingsRequest) (*RoundSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoundSettings not implemented")
}
func (UnimplementedSkyRushServer) GetActiveBets(context.Context, *GetActiveBetsRequest) (*GetActiveBetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveBets not implemented")
}
func (UnimplementedSkyRushServer) GetRoundHistory(context.Context, *GetRoundHistoryRequest) (*GetRoundHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoundHistory not implemented")
}
func (UnimplementedSkyRushServer) UpdateRoundSettings(context.Context, *RoundSettings) (*UpdateRoundSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoundSettings not implemented")
}

// UnsafeSkyRushServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkyRushServer will
// result in compilation errors.
type UnsafeSkyRushServer interface {
	mustEmbedUnimplementedSkyRushServer()
}

func RegisterSkyRushServer(s grpc.ServiceRegistrar, srv SkyRushServer) {
	s.RegisterService(&SkyRush_ServiceDesc, srv)
}

func _SkyRush_RoundCashout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoundBet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyRushServer).RoundCashout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkyRush/RoundCashout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyRushServer).RoundCashout(ctx, req.(*RoundBet))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyRush_PlaceRoundBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoundBet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyRushServer).PlaceRoundBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkyRush/PlaceRoundBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyRushServer).PlaceRoundBet(ctx, req.(*RoundBet))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyRush_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyRushServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkyRush/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyRushServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyRush_CancelRoundBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoundBet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyRushServer).CancelRoundBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkyRush/CancelRoundBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyRushServer).CancelRoundBet(ctx, req.(*RoundBet))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyRush_GetRoundBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoundBetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyRushServer).GetRoundBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkyRush/GetRoundBets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyRushServer).GetRoundBets(ctx, req.(*GetRoundBetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyRush_GetRoundSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoundSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyRushServer).GetRoundSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkyRush/GetRoundSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyRushServer).GetRoundSettings(ctx, req.(*GetRoundSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyRush_GetActiveBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveBetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyRushServer).GetActiveBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkyRush/GetActiveBets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyRushServer).GetActiveBets(ctx, req.(*GetActiveBetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyRush_GetRoundHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoundHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyRushServer).GetRoundHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkyRush/GetRoundHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyRushServer).GetRoundHistory(ctx, req.(*GetRoundHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyRush_UpdateRoundSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoundSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyRushServer).UpdateRoundSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkyRush/UpdateRoundSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyRushServer).UpdateRoundSettings(ctx, req.(*RoundSettings))
	}
	return interceptor(ctx, in, info, handler)
}

// SkyRush_ServiceDesc is the grpc.ServiceDesc for SkyRush service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkyRush_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SkyRush",
	HandlerType: (*SkyRushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RoundCashout",
			Handler:    _SkyRush_RoundCashout_Handler,
		},
		{
			MethodName: "PlaceRoundBet",
			Handler:    _SkyRush_PlaceRoundBet_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _SkyRush_Subscribe_Handler,
		},
		{
			MethodName: "CancelRoundBet",
			Handler:    _SkyRush_CancelRoundBet_Handler,
		},
		{
			MethodName: "GetRoundBets",
			Handler:    _SkyRush_GetRoundBets_Handler,
		},
		{
			MethodName: "GetRoundSettings",
			Handler:    _SkyRush_GetRoundSettings_Handler,
		},
		{
			MethodName: "GetActiveBets",
			Handler:    _SkyRush_GetActiveBets_Handler,
		},
		{
			MethodName: "GetRoundHistory",
			Handler:    _SkyRush_GetRoundHistory_Handler,
		},
		{
			MethodName: "UpdateRoundSettings",
			Handler:    _SkyRush_UpdateRoundSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messaging.proto",
}
