// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: soccer.simulator.proto

package services

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner   string `protobuf:"bytes,1,opt,name=Owner,proto3" json:"owner"`      
	Account string `protobuf:"bytes,2,opt,name=Account,proto3" json:"account"`  
	Status  string `protobuf:"bytes,3,opt,name=Status,proto3" json:"status"`    
	Page    string `protobuf:"bytes,4,opt,name=Page,proto3" json:"page"`        
}

func (x *GetBetsRequest) Reset() {
	*x = GetBetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBetsRequest) ProtoMessage() {}

func (x *GetBetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBetsRequest.ProtoReflect.Descriptor instead.
func (*GetBetsRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{0}
}

func (x *GetBetsRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetBetsRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GetBetsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetBetsRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

type GetBetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bets []*Bet `protobuf:"bytes,1,rep,name=Bets,proto3" json:"bets"`  
}

func (x *GetBetsResponse) Reset() {
	*x = GetBetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBetsResponse) ProtoMessage() {}

func (x *GetBetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBetsResponse.ProtoReflect.Descriptor instead.
func (*GetBetsResponse) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{1}
}

func (x *GetBetsResponse) GetBets() []*Bet {
	if x != nil {
		return x.Bets
	}
	return nil
}

type Bet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BetId       string  `protobuf:"bytes,1,opt,name=BetId,proto3" json:"id" bson:"_id"`                
	Payout      float64 `protobuf:"fixed64,2,opt,name=Payout,proto3" json:"payout" bson:"payout"`            
	Owner       string  `protobuf:"bytes,3,opt,name=Owner,proto3" json:"-" bson:"owner,omitempty"`                
	Type        string  `protobuf:"bytes,4,opt,name=Type,proto3" json:"type" bson:"type,omitempty"`                  
	Stake       float64 `protobuf:"fixed64,5,opt,name=Stake,proto3" json:"stake" bson:"stake,omitempty"`              
	Status      string  `protobuf:"bytes,6,opt,name=Status,proto3" json:"status" bson:"status,omitempty"`              
	Account     string  `protobuf:"bytes,7,opt,name=Account,proto3" json:"account" bson:"account,omitempty"`            
	MatchId     string  `protobuf:"bytes,8,opt,name=MatchId,proto3" json:"matchId" bson:"matchId,omitempty"`            
	Prediction  string  `protobuf:"bytes,9,opt,name=Prediction,proto3" json:"prediction" bson:"prediction,omitempty"`      
	DateCreated int64   `protobuf:"varint,10,opt,name=DateCreated,proto3" json:"dateCreated" bson:"dateCreated,omitempty"`  
}

func (x *Bet) Reset() {
	*x = Bet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bet) ProtoMessage() {}

func (x *Bet) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bet.ProtoReflect.Descriptor instead.
func (*Bet) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{2}
}

func (x *Bet) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *Bet) GetPayout() float64 {
	if x != nil {
		return x.Payout
	}
	return 0
}

func (x *Bet) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Bet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Bet) GetStake() float64 {
	if x != nil {
		return x.Stake
	}
	return 0
}

func (x *Bet) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Bet) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Bet) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *Bet) GetPrediction() string {
	if x != nil {
		return x.Prediction
	}
	return ""
}

func (x *Bet) GetDateCreated() int64 {
	if x != nil {
		return x.DateCreated
	}
	return 0
}

type Match struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string     `protobuf:"bytes,1,opt,name=ID,proto3" json:"id" form:"id" bson:"_id"`                      
	Type        string     `protobuf:"bytes,2,opt,name=Type,proto3" json:"type" form:"type" bson:"type"`                  
	Odds        *Odds      `protobuf:"bytes,3,opt,name=Odds,proto3" json:"odds" form:"odds" bson:"odds,omitempty"`                  
	Video       *Video     `protobuf:"bytes,4,opt,name=Video,proto3" json:"video" form:"video" bson:"video,omitempty"`                
	Title       string     `protobuf:"bytes,5,opt,name=Title,proto3" json:"title" form:"title" bson:"title,omitempty"`                
	League      *League    `protobuf:"bytes,6,opt,name=League,proto3" json:"league" form:"league" bson:"league,omitempty"`              
	Status      string     `protobuf:"bytes,7,opt,name=Status,proto3" json:"status" form:"status" bson:"status,omitempty"`              
	HomeTeam    *Team      `protobuf:"bytes,8,opt,name=HomeTeam,proto3" json:"homeTeam" form:"homeTeam" bson:"homeTeam,omitempty"`          
	AwayTeam    *Team      `protobuf:"bytes,9,opt,name=AwayTeam,proto3" json:"awayTeam" form:"awayTeam" bson:"awayTeam,omitempty"`          
	ScoreLine   *ScoreLine `protobuf:"bytes,10,opt,name=ScoreLine,proto3" json:"scoreline" form:"scoreline" bson:"scoreline,omitempty"`       
	StartTime   int64      `protobuf:"varint,11,opt,name=StartTime,proto3" json:"startTime" form:"startTime" bson:"startTime,omitempty"`      
	DateCreated int64      `protobuf:"varint,12,opt,name=DateCreated,proto3" json:"dateCreated" form:"dateCreated" bson:"dateCreated,omitempty"`  
	Outcomes    *Outcomes  `protobuf:"bytes,13,opt,name=Outcomes,proto3" json:"outcomes,omitempty" form:"outcomes" bson:"outcomes,omitempty"`         
}

func (x *Match) Reset() {
	*x = Match{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{3}
}

func (x *Match) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Match) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Match) GetOdds() *Odds {
	if x != nil {
		return x.Odds
	}
	return nil
}

func (x *Match) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *Match) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Match) GetLeague() *League {
	if x != nil {
		return x.League
	}
	return nil
}

func (x *Match) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Match) GetHomeTeam() *Team {
	if x != nil {
		return x.HomeTeam
	}
	return nil
}

func (x *Match) GetAwayTeam() *Team {
	if x != nil {
		return x.AwayTeam
	}
	return nil
}

func (x *Match) GetScoreLine() *ScoreLine {
	if x != nil {
		return x.ScoreLine
	}
	return nil
}

func (x *Match) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Match) GetDateCreated() int64 {
	if x != nil {
		return x.DateCreated
	}
	return 0
}

func (x *Match) GetOutcomes() *Outcomes {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

type Odds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Draw        float64 `protobuf:"fixed64,1,opt,name=Draw,proto3" json:"draw" bson:"draw"`                
	HomeTeamWin float64 `protobuf:"fixed64,2,opt,name=HomeTeamWin,proto3" json:"homeTeamWin" bson:"homeTeamWin"`  
	AwayTeamWin float64 `protobuf:"fixed64,3,opt,name=AwayTeamWin,proto3" json:"awayTeamWin" bson:"awayTeamWin"`  
}

func (x *Odds) Reset() {
	*x = Odds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Odds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Odds) ProtoMessage() {}

func (x *Odds) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Odds.ProtoReflect.Descriptor instead.
func (*Odds) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{4}
}

func (x *Odds) GetDraw() float64 {
	if x != nil {
		return x.Draw
	}
	return 0
}

func (x *Odds) GetHomeTeamWin() float64 {
	if x != nil {
		return x.HomeTeamWin
	}
	return 0
}

func (x *Odds) GetAwayTeamWin() float64 {
	if x != nil {
		return x.AwayTeamWin
	}
	return 0
}

type Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URI          string `protobuf:"bytes,1,opt,name=URI,proto3" json:"url" bson:"url"`                     
	PlaybackTime int64  `protobuf:"varint,2,opt,name=PlaybackTime,proto3" json:"playBackTime" bson:"-"`  
}

func (x *Video) Reset() {
	*x = Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{5}
}

func (x *Video) GetURI() string {
	if x != nil {
		return x.URI
	}
	return ""
}

func (x *Video) GetPlaybackTime() int64 {
	if x != nil {
		return x.PlaybackTime
	}
	return 0
}

type ScoreLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomeTeam int64 `protobuf:"varint,1,opt,name=HomeTeam,proto3" json:"homeTeam" bson:"homeTeam"`  
	AwayTeam int64 `protobuf:"varint,2,opt,name=AwayTeam,proto3" json:"awayTeam" bson:"awayTeam"`  
}

func (x *ScoreLine) Reset() {
	*x = ScoreLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreLine) ProtoMessage() {}

func (x *ScoreLine) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreLine.ProtoReflect.Descriptor instead.
func (*ScoreLine) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{6}
}

func (x *ScoreLine) GetHomeTeam() int64 {
	if x != nil {
		return x.HomeTeam
	}
	return 0
}

func (x *ScoreLine) GetAwayTeam() int64 {
	if x != nil {
		return x.AwayTeam
	}
	return 0
}

type Score struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomeTeam int64 `protobuf:"varint,1,opt,name=HomeTeam,proto3" json:"homeTeam" bson:"homeTeam"`  
	AwayTeam int64 `protobuf:"varint,2,opt,name=AwayTeam,proto3" json:"awayTeam" bson:"awayTeam"`  
	Time     int64 `protobuf:"varint,3,opt,name=Time,proto3" json:"time" form:"time" bson:"time,omitempty"`          
}

func (x *Score) Reset() {
	*x = Score{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{7}
}

func (x *Score) GetHomeTeam() int64 {
	if x != nil {
		return x.HomeTeam
	}
	return 0
}

func (x *Score) GetAwayTeam() int64 {
	if x != nil {
		return x.AwayTeam
	}
	return 0
}

func (x *Score) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Outcome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result       string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"-" bson:"-"`              
	Video        string   `protobuf:"bytes,2,opt,name=Video,proto3" json:"video" bson:"video"`                
	Duration     int64    `protobuf:"varint,3,opt,name=Duration,proto3" json:"duration" bson:"duration"`         
	ScoreHistory []*Score `protobuf:"bytes,4,rep,name=ScoreHistory,proto3" json:"scoreHistory" form:"scoreHistory" bson:"scoreHistory"`  
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{8}
}

func (x *Outcome) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Outcome) GetVideo() string {
	if x != nil {
		return x.Video
	}
	return ""
}

func (x *Outcome) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Outcome) GetScoreHistory() []*Score {
	if x != nil {
		return x.ScoreHistory
	}
	return nil
}

type Outcomes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Draw        *Outcome `protobuf:"bytes,1,opt,name=Draw,proto3" json:"draw,omitempty" form:"draw" bson:"draw,omitempty"`                
	HomeTeamWin *Outcome `protobuf:"bytes,2,opt,name=HomeTeamWin,proto3" json:"homeTeamWin,omitempty" form:"homeTeamWin" bson:"homeTeamWin,omitempty"`  
	AwayTeamWin *Outcome `protobuf:"bytes,3,opt,name=AwayTeamWin,proto3" json:"awayTeamWin,omitempty" form:"awayTeamWin" bson:"awayTeamWin,omitempty"`  
}

func (x *Outcomes) Reset() {
	*x = Outcomes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outcomes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcomes) ProtoMessage() {}

func (x *Outcomes) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcomes.ProtoReflect.Descriptor instead.
func (*Outcomes) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{9}
}

func (x *Outcomes) GetDraw() *Outcome {
	if x != nil {
		return x.Draw
	}
	return nil
}

func (x *Outcomes) GetHomeTeamWin() *Outcome {
	if x != nil {
		return x.HomeTeamWin
	}
	return nil
}

func (x *Outcomes) GetAwayTeamWin() *Outcome {
	if x != nil {
		return x.AwayTeamWin
	}
	return nil
}

type BetUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string  `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`    
	Balance float64 `protobuf:"fixed64,2,opt,name=Balance,proto3" json:"balance"`  
}

func (x *BetUpdateResponse) Reset() {
	*x = BetUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetUpdateResponse) ProtoMessage() {}

func (x *BetUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetUpdateResponse.ProtoReflect.Descriptor instead.
func (*BetUpdateResponse) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{10}
}

func (x *BetUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BetUpdateResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type UpdateBetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string  `protobuf:"bytes,1,opt,name=ID,proto3" json:"id" bson:"-"`                  
	Stake      float64 `protobuf:"fixed64,2,opt,name=Stake,proto3" json:"stake" bson:"stake"`          
	Prediction string  `protobuf:"bytes,3,opt,name=Prediction,proto3" json:"prediction" bson:"prediction"`  
}

func (x *UpdateBetRequest) Reset() {
	*x = UpdateBetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBetRequest) ProtoMessage() {}

func (x *UpdateBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBetRequest.ProtoReflect.Descriptor instead.
func (*UpdateBetRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateBetRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateBetRequest) GetStake() float64 {
	if x != nil {
		return x.Stake
	}
	return 0
}

func (x *UpdateBetRequest) GetPrediction() string {
	if x != nil {
		return x.Prediction
	}
	return ""
}

type ScheduleStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id" bson:"-"`                 
	Status    string `protobuf:"bytes,2,opt,name=Status,proto3" json:"-" bson:"status"`         
	StartTime int64  `protobuf:"varint,3,opt,name=StartTime,proto3" json:"startTime" bson:"startTime"`  
}

func (x *ScheduleStreamRequest) Reset() {
	*x = ScheduleStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleStreamRequest) ProtoMessage() {}

func (x *ScheduleStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleStreamRequest.ProtoReflect.Descriptor instead.
func (*ScheduleStreamRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{12}
}

func (x *ScheduleStreamRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ScheduleStreamRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScheduleStreamRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type ScheduleStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`  
}

func (x *ScheduleStreamResponse) Reset() {
	*x = ScheduleStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleStreamResponse) ProtoMessage() {}

func (x *ScheduleStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleStreamResponse.ProtoReflect.Descriptor instead.
func (*ScheduleStreamResponse) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{13}
}

func (x *ScheduleStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteBetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BetId string `protobuf:"bytes,1,opt,name=BetId,proto3" json:"betId"`  
}

func (x *DeleteBetRequest) Reset() {
	*x = DeleteBetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBetRequest) ProtoMessage() {}

func (x *DeleteBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBetRequest.ProtoReflect.Descriptor instead.
func (*DeleteBetRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteBetRequest) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

type League struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id" bson:"_id"`      
	Logo string `protobuf:"bytes,2,opt,name=Logo,proto3" json:"logo" bson:"logo,omitempty"`  
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"name" bson:"name" form:"name"`  
}

func (x *League) Reset() {
	*x = League{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *League) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*League) ProtoMessage() {}

func (x *League) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use League.ProtoReflect.Descriptor instead.
func (*League) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{15}
}

func (x *League) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *League) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *League) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddLeagueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	League string `protobuf:"bytes,1,opt,name=League,proto3" json:"league"`  
	Logo   *File  `protobuf:"bytes,2,opt,name=Logo,proto3" json:"logo"`      
}

func (x *AddLeagueRequest) Reset() {
	*x = AddLeagueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLeagueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLeagueRequest) ProtoMessage() {}

func (x *AddLeagueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLeagueRequest.ProtoReflect.Descriptor instead.
func (*AddLeagueRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{16}
}

func (x *AddLeagueRequest) GetLeague() string {
	if x != nil {
		return x.League
	}
	return ""
}

func (x *AddLeagueRequest) GetLogo() *File {
	if x != nil {
		return x.Logo
	}
	return nil
}

type AddLeagueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string  `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`  
	League  *League `protobuf:"bytes,2,opt,name=League,proto3" json:"league"`    
}

func (x *AddLeagueResponse) Reset() {
	*x = AddLeagueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLeagueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLeagueResponse) ProtoMessage() {}

func (x *AddLeagueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLeagueResponse.ProtoReflect.Descriptor instead.
func (*AddLeagueResponse) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{17}
}

func (x *AddLeagueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddLeagueResponse) GetLeague() *League {
	if x != nil {
		return x.League
	}
	return nil
}

type GetLeaguesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Leagues []*League `protobuf:"bytes,1,rep,name=Leagues,proto3" json:"leagues"`  
}

func (x *GetLeaguesResponse) Reset() {
	*x = GetLeaguesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLeaguesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaguesResponse) ProtoMessage() {}

func (x *GetLeaguesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaguesResponse.ProtoReflect.Descriptor instead.
func (*GetLeaguesResponse) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{18}
}

func (x *GetLeaguesResponse) GetLeagues() []*League {
	if x != nil {
		return x.Leagues
	}
	return nil
}

type DeleteLeagueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id"`  
}

func (x *DeleteLeagueRequest) Reset() {
	*x = DeleteLeagueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLeagueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeagueRequest) ProtoMessage() {}

func (x *DeleteLeagueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeagueRequest.ProtoReflect.Descriptor instead.
func (*DeleteLeagueRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteLeagueRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteLeagueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`  
}

func (x *DeleteLeagueResponse) Reset() {
	*x = DeleteLeagueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLeagueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeagueResponse) ProtoMessage() {}

func (x *DeleteLeagueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeagueResponse.ProtoReflect.Descriptor instead.
func (*DeleteLeagueResponse) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteLeagueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Team struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id" bson:"_id"`                
	Logo      string `protobuf:"bytes,2,opt,name=Logo,proto3" json:"logo" bson:"logo,omitempty"`            
	Name      string `protobuf:"bytes,3,opt,name=Name,proto3" json:"name" bson:"name,omitempty" form:"name"`            
	ShortName string `protobuf:"bytes,4,opt,name=ShortName,proto3" json:"shortName" bson:"shortName,omitempty" form:"shortName"`  
}

func (x *Team) Reset() {
	*x = Team{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{21}
}

func (x *Team) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Team) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

type AddTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team *Team `protobuf:"bytes,1,opt,name=Team,proto3" json:"team"`  
	Logo *File `protobuf:"bytes,2,opt,name=Logo,proto3" json:"logo"`  
}

func (x *AddTeamRequest) Reset() {
	*x = AddTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamRequest) ProtoMessage() {}

func (x *AddTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamRequest.ProtoReflect.Descriptor instead.
func (*AddTeamRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{22}
}

func (x *AddTeamRequest) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

func (x *AddTeamRequest) GetLogo() *File {
	if x != nil {
		return x.Logo
	}
	return nil
}

type GetTeamsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teams []*Team `protobuf:"bytes,1,rep,name=Teams,proto3" json:"teams"`  
}

func (x *GetTeamsResponse) Reset() {
	*x = GetTeamsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsResponse) ProtoMessage() {}

func (x *GetTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsResponse.ProtoReflect.Descriptor instead.
func (*GetTeamsResponse) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{23}
}

func (x *GetTeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type AddTeamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`  
	Team    *Team  `protobuf:"bytes,2,opt,name=Team,proto3" json:"team"`        
}

func (x *AddTeamResponse) Reset() {
	*x = AddTeamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamResponse) ProtoMessage() {}

func (x *AddTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamResponse.ProtoReflect.Descriptor instead.
func (*AddTeamResponse) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{24}
}

func (x *AddTeamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type DeleteTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id"`  
}

func (x *DeleteTeamRequest) Reset() {
	*x = DeleteTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequest) ProtoMessage() {}

func (x *DeleteTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteTeamRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteTeamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`  
}

func (x *DeleteTeamResponse) Reset() {
	*x = DeleteTeamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamResponse) ProtoMessage() {}

func (x *DeleteTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamResponse) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteTeamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMatchesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=Status,proto3" json:"status"`  
	Type   string `protobuf:"bytes,2,opt,name=Type,proto3" json:"type"`      
	Page   string `protobuf:"bytes,3,opt,name=Page,proto3" json:"page"`      
	Limit  int64  `protobuf:"varint,4,opt,name=Limit,proto3" json:"limit"`   
}

func (x *GetMatchesRequest) Reset() {
	*x = GetMatchesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchesRequest) ProtoMessage() {}

func (x *GetMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchesRequest.ProtoReflect.Descriptor instead.
func (*GetMatchesRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{27}
}

func (x *GetMatchesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMatchesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetMatchesRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *GetMatchesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMatchesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Matches []*Match `protobuf:"bytes,1,rep,name=Matches,proto3" json:"matches"`  
}

func (x *GetMatchesResponse) Reset() {
	*x = GetMatchesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchesResponse) ProtoMessage() {}

func (x *GetMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchesResponse.ProtoReflect.Descriptor instead.
func (*GetMatchesResponse) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{28}
}

func (x *GetMatchesResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GetMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id"`  
}

func (x *GetMatchRequest) Reset() {
	*x = GetMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchRequest) ProtoMessage() {}

func (x *GetMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchRequest.ProtoReflect.Descriptor instead.
func (*GetMatchRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{29}
}

func (x *GetMatchRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type AddMatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"message"`  
	Match   *Match `protobuf:"bytes,2,opt,name=Match,proto3" json:"match"`      
}

func (x *AddMatchResponse) Reset() {
	*x = AddMatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMatchResponse) ProtoMessage() {}

func (x *AddMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMatchResponse.ProtoReflect.Descriptor instead.
func (*AddMatchResponse) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{30}
}

func (x *AddMatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddMatchResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type UpdateMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id" bson:"_id"`        
	Title string `protobuf:"bytes,2,opt,name=Title,proto3" json:"title" bson:"title,omitempty"`  
}

func (x *UpdateMatchRequest) Reset() {
	*x = UpdateMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMatchRequest) ProtoMessage() {}

func (x *UpdateMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMatchRequest.ProtoReflect.Descriptor instead.
func (*UpdateMatchRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateMatchRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateMatchRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ReuseMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id" bson:"_id"`  
}

func (x *ReuseMatchRequest) Reset() {
	*x = ReuseMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReuseMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReuseMatchRequest) ProtoMessage() {}

func (x *ReuseMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReuseMatchRequest.ProtoReflect.Descriptor instead.
func (*ReuseMatchRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{32}
}

func (x *ReuseMatchRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"data"`          
	Filename string `protobuf:"bytes,2,opt,name=Filename,proto3" json:"fileName"`  
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{33}
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type AddOutcomesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id" bson:"_id"`              
	Outcomes string `protobuf:"bytes,2,opt,name=Outcomes,proto3" json:"outcomes" bson:"outcomes"`  
	Video    *File  `protobuf:"bytes,3,opt,name=Video,proto3" json:"video" bson:"video"`        
}

func (x *AddOutcomesRequest) Reset() {
	*x = AddOutcomesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOutcomesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOutcomesRequest) ProtoMessage() {}

func (x *AddOutcomesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOutcomesRequest.ProtoReflect.Descriptor instead.
func (*AddOutcomesRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{34}
}

func (x *AddOutcomesRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AddOutcomesRequest) GetOutcomes() string {
	if x != nil {
		return x.Outcomes
	}
	return ""
}

func (x *AddOutcomesRequest) GetVideo() *File {
	if x != nil {
		return x.Video
	}
	return nil
}

type DeleteMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id"`  
}

func (x *DeleteMatchRequest) Reset() {
	*x = DeleteMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soccer_simulator_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMatchRequest) ProtoMessage() {}

func (x *DeleteMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soccer_simulator_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteMatchRequest) Descriptor() ([]byte, []int) {
	return file_soccer_simulator_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteMatchRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_soccer_simulator_proto protoreflect.FileDescriptor

var file_soccer_simulator_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x6f, 0x63, 0x63, 0x65, 0x72, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50,
	0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x04, 0x42, 0x65, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x42, 0x65, 0x74, 0x52, 0x04, 0x42, 0x65, 0x74, 0x73,
	0x22, 0x81, 0x02, 0x0a, 0x03, 0x42, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x65, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x42, 0x65, 0x74, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x50, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x50, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x44, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x22, 0x8a, 0x03, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x4f, 0x64, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x4f, 0x64, 0x64, 0x73, 0x52, 0x04, 0x4f, 0x64, 0x64, 0x73, 0x12, 0x1c, 0x0a,
	0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x52, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x1f, 0x0a, 0x06, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x52, 0x06, 0x4c, 0x65, 0x61, 0x67,
	0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x08, 0x48, 0x6f,
	0x6d, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x54,
	0x65, 0x61, 0x6d, 0x52, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x21, 0x0a,
	0x08, 0x41, 0x77, 0x61, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x08, 0x41, 0x77, 0x61, 0x79, 0x54, 0x65, 0x61, 0x6d,
	0x12, 0x28, 0x0a, 0x09, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x52,
	0x09, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x44,
	0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x08, 0x4f, 0x75,
	0x74, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4f,
	0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x52, 0x08, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65,
	0x73, 0x22, 0x5e, 0x0a, 0x04, 0x4f, 0x64, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x72, 0x61,
	0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x44, 0x72, 0x61, 0x77, 0x12, 0x20, 0x0a,
	0x0b, 0x48, 0x6f, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x57, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0b, 0x48, 0x6f, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x57, 0x69, 0x6e, 0x12,
	0x20, 0x0a, 0x0b, 0x41, 0x77, 0x61, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x57, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x41, 0x77, 0x61, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x57, 0x69,
	0x6e, 0x22, 0x3d, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52,
	0x49, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x49, 0x12, 0x22, 0x0a, 0x0c,
	0x50, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x43, 0x0a, 0x09, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x48, 0x6f, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x48, 0x6f, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x77, 0x61,
	0x79, 0x54, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x41, 0x77, 0x61,
	0x79, 0x54, 0x65, 0x61, 0x6d, 0x22, 0x53, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x77,
	0x61, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x41, 0x77,
	0x61, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x7f, 0x0a, 0x07, 0x4f, 0x75,
	0x74, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2a, 0x0a, 0x0c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x0c, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x80, 0x01, 0x0a, 0x08,
	0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x04, 0x44, 0x72, 0x61, 0x77,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65,
	0x52, 0x04, 0x44, 0x72, 0x61, 0x77, 0x12, 0x2a, 0x0a, 0x0b, 0x48, 0x6f, 0x6d, 0x65, 0x54, 0x65,
	0x61, 0x6d, 0x57, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4f, 0x75,
	0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x0b, 0x48, 0x6f, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x57,
	0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x0b, 0x41, 0x77, 0x61, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x57, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d,
	0x65, 0x52, 0x0b, 0x41, 0x77, 0x61, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x57, 0x69, 0x6e, 0x22, 0x47,
	0x0a, 0x11, 0x42, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x58, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x53, 0x74, 0x61, 0x6b,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x5d, 0x0a, 0x15, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x32, 0x0a, 0x16, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x65, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x42, 0x65, 0x74, 0x49, 0x64, 0x22, 0x40,
	0x0a, 0x06, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x67, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x6f, 0x67, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x45, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x04,
	0x4c, 0x6f, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x04, 0x4c, 0x6f, 0x67, 0x6f, 0x22, 0x4e, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x4c, 0x65,
	0x61, 0x67, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x52,
	0x06, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x65,
	0x61, 0x67, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x07, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x52, 0x07, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x73,
	0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5c, 0x0a, 0x04, 0x54, 0x65, 0x61,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4c, 0x6f, 0x67, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x54, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x54, 0x65, 0x61,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x04,
	0x54, 0x65, 0x61, 0x6d, 0x12, 0x19, 0x0a, 0x04, 0x4c, 0x6f, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x4c, 0x6f, 0x67, 0x6f, 0x22,
	0x2f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x54, 0x65, 0x61, 0x6d, 0x73,
	0x22, 0x46, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a,
	0x04, 0x54, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x54, 0x65,
	0x61, 0x6d, 0x52, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x2e, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x69, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x36, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x07, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x07, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73,
	0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x22, 0x4a, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1c, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x06, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x22,
	0x3a, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x52,
	0x65, 0x75, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x22, 0x36, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5d, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4f,
	0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x05, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x32, 0xc9, 0x07,
	0x0a, 0x0f, 0x53, 0x6f, 0x63, 0x63, 0x65, 0x72, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x22, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x05, 0x2e, 0x54,
	0x65, 0x61, 0x6d, 0x1a, 0x10, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65,
	0x74, 0x12, 0x04, 0x2e, 0x42, 0x65, 0x74, 0x1a, 0x12, 0x2e, 0x42, 0x65, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x25, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x06, 0x2e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x11, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x05, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x1a, 0x10, 0x2e,
	0x41, 0x64, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x12, 0x07, 0x2e, 0x4c,
	0x65, 0x61, 0x67, 0x75, 0x65, 0x1a, 0x12, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x65, 0x61, 0x67, 0x75,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x42, 0x65, 0x74, 0x73, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x42, 0x65, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x42, 0x65,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x0a, 0x52, 0x65, 0x75, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x12, 0x2e,
	0x52, 0x65, 0x75, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x13, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x41,
	0x64, 0x64, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x41, 0x64, 0x64,
	0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x13, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x12,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x12, 0x14, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x16, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x64, 0x69, 0x76, 0x69, 0x6e,
	0x65, 0x7a, 0x2f, 0x73, 0x6f, 0x63, 0x63, 0x65, 0x72, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_soccer_simulator_proto_rawDescOnce sync.Once
	file_soccer_simulator_proto_rawDescData = file_soccer_simulator_proto_rawDesc
)

func file_soccer_simulator_proto_rawDescGZIP() []byte {
	file_soccer_simulator_proto_rawDescOnce.Do(func() {
		file_soccer_simulator_proto_rawDescData = protoimpl.X.CompressGZIP(file_soccer_simulator_proto_rawDescData)
	})
	return file_soccer_simulator_proto_rawDescData
}

var file_soccer_simulator_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_soccer_simulator_proto_goTypes = []any{
	(*GetBetsRequest)(nil),         // 0: GetBetsRequest
	(*GetBetsResponse)(nil),        // 1: GetBetsResponse
	(*Bet)(nil),                    // 2: Bet
	(*Match)(nil),                  // 3: Match
	(*Odds)(nil),                   // 4: Odds
	(*Video)(nil),                  // 5: Video
	(*ScoreLine)(nil),              // 6: ScoreLine
	(*Score)(nil),                  // 7: Score
	(*Outcome)(nil),                // 8: Outcome
	(*Outcomes)(nil),               // 9: Outcomes
	(*BetUpdateResponse)(nil),      // 10: BetUpdateResponse
	(*UpdateBetRequest)(nil),       // 11: UpdateBetRequest
	(*ScheduleStreamRequest)(nil),  // 12: ScheduleStreamRequest
	(*ScheduleStreamResponse)(nil), // 13: ScheduleStreamResponse
	(*DeleteBetRequest)(nil),       // 14: DeleteBetRequest
	(*League)(nil),                 // 15: League
	(*AddLeagueRequest)(nil),       // 16: AddLeagueRequest
	(*AddLeagueResponse)(nil),      // 17: AddLeagueResponse
	(*GetLeaguesResponse)(nil),     // 18: GetLeaguesResponse
	(*DeleteLeagueRequest)(nil),    // 19: DeleteLeagueRequest
	(*DeleteLeagueResponse)(nil),   // 20: DeleteLeagueResponse
	(*Team)(nil),                   // 21: Team
	(*AddTeamRequest)(nil),         // 22: AddTeamRequest
	(*GetTeamsResponse)(nil),       // 23: GetTeamsResponse
	(*AddTeamResponse)(nil),        // 24: AddTeamResponse
	(*DeleteTeamRequest)(nil),      // 25: DeleteTeamRequest
	(*DeleteTeamResponse)(nil),     // 26: DeleteTeamResponse
	(*GetMatchesRequest)(nil),      // 27: GetMatchesRequest
	(*GetMatchesResponse)(nil),     // 28: GetMatchesResponse
	(*GetMatchRequest)(nil),        // 29: GetMatchRequest
	(*AddMatchResponse)(nil),       // 30: AddMatchResponse
	(*UpdateMatchRequest)(nil),     // 31: UpdateMatchRequest
	(*ReuseMatchRequest)(nil),      // 32: ReuseMatchRequest
	(*File)(nil),                   // 33: File
	(*AddOutcomesRequest)(nil),     // 34: AddOutcomesRequest
	(*DeleteMatchRequest)(nil),     // 35: DeleteMatchRequest
	(*empty.Empty)(nil),            // 36: google.protobuf.Empty
}
var file_soccer_simulator_proto_depIdxs = []int32{
	2,  // 0: GetBetsResponse.Bets:type_name -> Bet
	4,  // 1: Match.Odds:type_name -> Odds
	5,  // 2: Match.Video:type_name -> Video
	15, // 3: Match.League:type_name -> League
	21, // 4: Match.HomeTeam:type_name -> Team
	21, // 5: Match.AwayTeam:type_name -> Team
	6,  // 6: Match.ScoreLine:type_name -> ScoreLine
	9,  // 7: Match.Outcomes:type_name -> Outcomes
	7,  // 8: Outcome.ScoreHistory:type_name -> Score
	8,  // 9: Outcomes.Draw:type_name -> Outcome
	8,  // 10: Outcomes.HomeTeamWin:type_name -> Outcome
	8,  // 11: Outcomes.AwayTeamWin:type_name -> Outcome
	33, // 12: AddLeagueRequest.Logo:type_name -> File
	15, // 13: AddLeagueResponse.League:type_name -> League
	15, // 14: GetLeaguesResponse.Leagues:type_name -> League
	21, // 15: AddTeamRequest.Team:type_name -> Team
	33, // 16: AddTeamRequest.Logo:type_name -> File
	21, // 17: GetTeamsResponse.Teams:type_name -> Team
	21, // 18: AddTeamResponse.Team:type_name -> Team
	3,  // 19: GetMatchesResponse.Matches:type_name -> Match
	3,  // 20: AddMatchResponse.Match:type_name -> Match
	33, // 21: AddOutcomesRequest.Video:type_name -> File
	21, // 22: SoccerSimulator.AddTeam:input_type -> Team
	2,  // 23: SoccerSimulator.PlaceBet:input_type -> Bet
	29, // 24: SoccerSimulator.GetMatch:input_type -> GetMatchRequest
	3,  // 25: SoccerSimulator.AddMatch:input_type -> Match
	21, // 26: SoccerSimulator.UpdateTeam:input_type -> Team
	15, // 27: SoccerSimulator.AddLeague:input_type -> League
	0,  // 28: SoccerSimulator.GetBets:input_type -> GetBetsRequest
	14, // 29: SoccerSimulator.DeleteBet:input_type -> DeleteBetRequest
	11, // 30: SoccerSimulator.UpdateBet:input_type -> UpdateBetRequest
	32, // 31: SoccerSimulator.ReuseMatch:input_type -> ReuseMatchRequest
	35, // 32: SoccerSimulator.DeleteMatch:input_type -> DeleteMatchRequest
	34, // 33: SoccerSimulator.AddOutcomes:input_type -> AddOutcomesRequest
	31, // 34: SoccerSimulator.UpdateMatch:input_type -> UpdateMatchRequest
	36, // 35: SoccerSimulator.GetTeams:input_type -> google.protobuf.Empty
	27, // 36: SoccerSimulator.GetMatches:input_type -> GetMatchesRequest
	25, // 37: SoccerSimulator.DeleteTeam:input_type -> DeleteTeamRequest
	36, // 38: SoccerSimulator.GetLeagues:input_type -> google.protobuf.Empty
	19, // 39: SoccerSimulator.DeleteLeague:input_type -> DeleteLeagueRequest
	12, // 40: SoccerSimulator.ScheduleStream:input_type -> ScheduleStreamRequest
	24, // 41: SoccerSimulator.AddTeam:output_type -> AddTeamResponse
	10, // 42: SoccerSimulator.PlaceBet:output_type -> BetUpdateResponse
	3,  // 43: SoccerSimulator.GetMatch:output_type -> Match
	30, // 44: SoccerSimulator.AddMatch:output_type -> AddMatchResponse
	24, // 45: SoccerSimulator.UpdateTeam:output_type -> AddTeamResponse
	17, // 46: SoccerSimulator.AddLeague:output_type -> AddLeagueResponse
	1,  // 47: SoccerSimulator.GetBets:output_type -> GetBetsResponse
	10, // 48: SoccerSimulator.DeleteBet:output_type -> BetUpdateResponse
	10, // 49: SoccerSimulator.UpdateBet:output_type -> BetUpdateResponse
	30, // 50: SoccerSimulator.ReuseMatch:output_type -> AddMatchResponse
	30, // 51: SoccerSimulator.DeleteMatch:output_type -> AddMatchResponse
	30, // 52: SoccerSimulator.AddOutcomes:output_type -> AddMatchResponse
	30, // 53: SoccerSimulator.UpdateMatch:output_type -> AddMatchResponse
	23, // 54: SoccerSimulator.GetTeams:output_type -> GetTeamsResponse
	28, // 55: SoccerSimulator.GetMatches:output_type -> GetMatchesResponse
	26, // 56: SoccerSimulator.DeleteTeam:output_type -> DeleteTeamResponse
	18, // 57: SoccerSimulator.GetLeagues:output_type -> GetLeaguesResponse
	20, // 58: SoccerSimulator.DeleteLeague:output_type -> DeleteLeagueResponse
	13, // 59: SoccerSimulator.ScheduleStream:output_type -> ScheduleStreamResponse
	41, // [41:60] is the sub-list for method output_type
	22, // [22:41] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_soccer_simulator_proto_init() }
func file_soccer_simulator_proto_init() {
	if File_soccer_simulator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_soccer_simulator_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetBetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetBetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Bet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Match); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Odds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ScoreLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Score); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Outcome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Outcomes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*BetUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateBetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ScheduleStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*ScheduleStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*League); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*AddLeagueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*AddLeagueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*GetLeaguesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteLeagueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteLeagueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*Team); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*AddTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*GetTeamsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*AddTeamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTeamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*GetMatchesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*GetMatchesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*GetMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[30].Exporter = func(v any, i int) any {
			switch v := v.(*AddMatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[31].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[32].Exporter = func(v any, i int) any {
			switch v := v.(*ReuseMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[33].Exporter = func(v any, i int) any {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[34].Exporter = func(v any, i int) any {
			switch v := v.(*AddOutcomesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soccer_simulator_proto_msgTypes[35].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_soccer_simulator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_soccer_simulator_proto_goTypes,
		DependencyIndexes: file_soccer_simulator_proto_depIdxs,
		MessageInfos:      file_soccer_simulator_proto_msgTypes,
	}.Build()
	File_soccer_simulator_proto = out.File
	file_soccer_simulator_proto_rawDesc = nil
	file_soccer_simulator_proto_goTypes = nil
	file_soccer_simulator_proto_depIdxs = nil
}
