// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: rps.proto

package rps

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RockPaperScissorsClient is the client API for RockPaperScissors service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RockPaperScissorsClient interface {
	RPSPlaceBet(ctx context.Context, in *RPSPlaceBetRequest, opts ...grpc.CallOption) (*RPSPlaceBetResponse, error)
}

type rockPaperScissorsClient struct {
	cc grpc.ClientConnInterface
}

func NewRockPaperScissorsClient(cc grpc.ClientConnInterface) RockPaperScissorsClient {
	return &rockPaperScissorsClient{cc}
}

func (c *rockPaperScissorsClient) RPSPlaceBet(ctx context.Context, in *RPSPlaceBetRequest, opts ...grpc.CallOption) (*RPSPlaceBetResponse, error) {
	out := new(RPSPlaceBetResponse)
	err := c.cc.Invoke(ctx, "/RockPaperScissors/RPSPlaceBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RockPaperScissorsServer is the server API for RockPaperScissors service.
// All implementations should embed UnimplementedRockPaperScissorsServer
// for forward compatibility
type RockPaperScissorsServer interface {
	RPSPlaceBet(context.Context, *RPSPlaceBetRequest) (*RPSPlaceBetResponse, error)
}

// UnimplementedRockPaperScissorsServer should be embedded to have forward compatible implementations.
type UnimplementedRockPaperScissorsServer struct {
}

func (UnimplementedRockPaperScissorsServer) RPSPlaceBet(context.Context, *RPSPlaceBetRequest) (*RPSPlaceBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPSPlaceBet not implemented")
}

// UnsafeRockPaperScissorsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RockPaperScissorsServer will
// result in compilation errors.
type UnsafeRockPaperScissorsServer interface {
	mustEmbedUnimplementedRockPaperScissorsServer()
}

func RegisterRockPaperScissorsServer(s grpc.ServiceRegistrar, srv RockPaperScissorsServer) {
	s.RegisterService(&RockPaperScissors_ServiceDesc, srv)
}

func _RockPaperScissors_RPSPlaceBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPSPlaceBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RockPaperScissorsServer).RPSPlaceBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RockPaperScissors/RPSPlaceBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RockPaperScissorsServer).RPSPlaceBet(ctx, req.(*RPSPlaceBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RockPaperScissors_ServiceDesc is the grpc.ServiceDesc for RockPaperScissors service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RockPaperScissors_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RockPaperScissors",
	HandlerType: (*RockPaperScissorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RPSPlaceBet",
			Handler:    _RockPaperScissors_RPSPlaceBet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rps.proto",
}
